CREATE TABLE customer (Id INTEGER NOT NULL, Email VARCHAR(255), Enabled INTEGER, FullName VARCHAR(255), Password VARCHAR(255), PRIMARY KEY (Id))
CREATE TABLE authorities (Id INTEGER AUTO_INCREMENT NOT NULL, Authority VARCHAR(255), Email VARCHAR(255), PRIMARY KEY (Id))
CREATE TABLE book (Id INTEGER AUTO_INCREMENT NOT NULL, Author VARCHAR(255), CountPage INTEGER, Genre VARCHAR(255), Path VARCHAR(255), Title VARCHAR(255), PRIMARY KEY (Id))
